package oc.wh40k.armies;

import com.google.common.collect.ImmutableList;
import oc.BuildaHQ;
import oc.BuildaVater;
import oc.utils.ResourceUtils;
import oc.wh40k.units.or.*;

public class VOLKOrks extends BuildaVater {

    public VOLKOrks() {
        super("OR", ResourceUtils.loadPoints("/oc/wh40k/indices/or.yaml"));

        volk = "Orks";
        nameDerArtDerArmee = "Orks";
        nameDerArtDerArmeeDekliniert = "der Orks";

        textAreaUeberschrift = BuildaHQ.translate("Mein") + " Waaagh!";

        formationen.add("ORK");
        formationen.add("Goff");
        formationen.add("Blood Axe");
        formationen.add("Deathskulls");
        formationen.add("Evil Sunz");
        formationen.add("Snakebites");
        formationen.add("Bad Moonz");
        formationen.add("Freebooterz");

        complete();
    }

    @Override
    public void volkRefresh() {
        if (getFormationType().equals("ORK")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORWarboss.class,
                    ORDeffkillaWartrike.class,
                    null,
                    ORBigMekinMegaArmour.class,
                    ORBigMekwithShokkAttackGun.class,
                    null,
                    ORWeirdboy.class,
                    null,
                    ORGhazghkullThraka.class,
                    ORKaptinBadrukk.class,
                    ORBossZagstruk.class,
                    ORBossSnikrot.class,
                    null,
                    ORWarbossinMegaArmour.class,
                    ORWarbossonWarbike.class,
                    ORBigMek.class,
                    ORBigMekonWarbike.class,
                    null,
                    ORZhadsnarkdaRippa.class,
                    OROrkMekBossBuzzgob.class));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORBoyz.class,
                    ORGretchin.class));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORMek.class,
                    ORPainboy.class,
                    ORRuntherd.class,
                    null,
                    ORBurnaBoyz.class,
                    ORTankbustas.class,
                    ORKommandos.class,
                    null,
                    ORNobz.class,
                    ORNobwithWaaaghBanner.class,
                    ORNobzonWarbikes.class,
                    ORMeganobz.class,
                    null,
                    ORMadDokGrotsnik.class,
                    null,
                    ORPainboyonWarbike.class));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORStormboyz.class,
                    ORDeffkoptas.class,
                    ORWarbikers.class,
                    null,
                    ORKustomBoostaBlastas.class,
                    ORShokkjumpDragstas.class,
                    ORBoomdakkaSnazzwagons.class,
                    ORRukkatrukkSquigbuggys.class,
                    ORMegatrakkScrapjet.class,
                    null,
                    ORWartrakks.class,
                    ORSkorchas.class,
                    ORWarbuggies.class,
                    null,
                    ORGrotTanks.class,
                    ORGrotMegaTank.class));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORDeffDreads.class,
                    ORKillaKans.class,
                    null,
                    ORGorkanaut.class,
                    ORMorkanaut.class,
                    null,
                    ORBattlewagon.class,
                    ORGunwagon.class,
                    ORBonebreaka.class,
                    null,
                    ORMekGunz.class,
                    ORLootas.class,
                    ORFlashGitz.class,
                    null,
                    ORBigGunz.class,
                    null,
                    ORSquiggoth.class,
                    ORMekaDread.class,
                    ORLiftaWagon.class,
                    ORBigTrakk.class,
                    ORBattlewagonwithSupaKannon.class));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORTrukk.class,
                    null,
                    ORChinorkWarkopta.class));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORDakkajet.class,
                    ORBurnaBommer.class,
                    ORBlitzaBommer.class,
                    ORWazbomBlastajet.class));
            myChooserGruppen.get(LORD_OF_WAR).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORStompa.class,
                    null,
                    ORKillTank.class,
                    ORKustomStompa.class,
                    ORGargantuanSquiggoth.class));
        } else if (getFormationType().equals("Goff")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORWarboss.class,
                    ORDeffkillaWartrike.class,
                    null,
                    ORBigMekinMegaArmour.class,
                    ORBigMekwithShokkAttackGun.class,
                    null,
                    ORWeirdboy.class,
                    null,
                    ORKaptinBadrukk.class,
                    ORGhazghkullThraka.class,
                    ORBossZagstruk.class,
                    null,
                    ORWarbossinMegaArmour.class,
                    ORWarbossonWarbike.class,
                    ORBigMek.class,
                    ORBigMekonWarbike.class,
                    null,
                    OROrkMekBossBuzzgob.class));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORBoyz.class,
                    ORGretchin.class));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORMek.class,
                    ORPainboy.class,
                    ORPainboyonWarbike.class,
                    ORRuntherd.class,
                    null,
                    ORBurnaBoyz.class,
                    ORTankbustas.class,
                    ORNobz.class,
                    ORNobwithWaaaghBanner.class,
                    ORNobzonWarbikes.class,
                    ORMeganobz.class,
                    ORKommandos.class));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORStormboyz.class,
                    ORDeffkoptas.class,
                    ORWarbikers.class,
                    ORKustomBoostaBlastas.class,
                    ORShokkjumpDragstas.class,
                    ORBoomdakkaSnazzwagons.class,
                    ORRukkatrukkSquigbuggys.class,
                    ORMegatrakkScrapjet.class,
                    null,
                    ORWartrakks.class,
                    ORSkorchas.class,
                    ORWarbuggies.class,
                    null,
                    ORGrotTanks.class,
                    ORGrotMegaTank.class));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORDeffDreads.class,
                    ORKillaKans.class,
                    ORGorkanaut.class,
                    ORMorkanaut.class,
                    ORBattlewagon.class,
                    ORGunwagon.class,
                    ORBonebreaka.class,
                    ORBigGunz.class,
                    ORMekGunz.class,
                    ORLootas.class,
                    ORFlashGitz.class,
                    null,
                    ORSquiggoth.class,
                    ORMekaDread.class,
                    ORLiftaWagon.class,
                    ORBigTrakk.class,
                    ORBattlewagonwithSupaKannon.class));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORTrukk.class));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORDakkajet.class,
                    ORBurnaBommer.class,
                    ORBlitzaBommer.class,
                    ORWazbomBlastajet.class));
            myChooserGruppen.get(LORD_OF_WAR).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORStompa.class));
        } else if (getFormationType().equals("Blood Axe")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORWarboss.class,
                    ORDeffkillaWartrike.class,
                    null,
                    ORBigMekinMegaArmour.class,
                    ORBigMekwithShokkAttackGun.class,
                    null,
                    ORWeirdboy.class,
                    null,
                    ORKaptinBadrukk.class,
                    ORBossSnikrot.class,
                    null,
                    ORWarbossinMegaArmour.class,
                    ORWarbossonWarbike.class,
                    ORBigMek.class,
                    ORBigMekonWarbike.class));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORBoyz.class,
                    ORGretchin.class));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORMek.class,
                    ORPainboy.class,
                    ORPainboyonWarbike.class,
                    ORRuntherd.class,
                    null,
                    ORBurnaBoyz.class,
                    ORTankbustas.class,
                    ORNobz.class,
                    ORNobwithWaaaghBanner.class,
                    ORNobzonWarbikes.class,
                    ORMeganobz.class,
                    ORKommandos.class));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORStormboyz.class,
                    ORDeffkoptas.class,
                    ORWarbikers.class,
                    ORKustomBoostaBlastas.class,
                    ORShokkjumpDragstas.class,
                    ORBoomdakkaSnazzwagons.class,
                    ORRukkatrukkSquigbuggys.class,
                    ORMegatrakkScrapjet.class,
                    null,
                    ORWartrakks.class,
                    ORSkorchas.class,
                    ORWarbuggies.class,
                    null,
                    ORGrotTanks.class,
                    ORGrotMegaTank.class));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORDeffDreads.class,
                    ORKillaKans.class,
                    ORGorkanaut.class,
                    ORMorkanaut.class,
                    ORBattlewagon.class,
                    ORGunwagon.class,
                    ORBonebreaka.class,
                    ORBigGunz.class,
                    ORMekGunz.class,
                    ORLootas.class,
                    ORFlashGitz.class,
                    null,
                    ORSquiggoth.class,
                    ORMekaDread.class,
                    ORLiftaWagon.class,
                    ORBigTrakk.class,
                    ORBattlewagonwithSupaKannon.class));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORTrukk.class));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORDakkajet.class,
                    ORBurnaBommer.class,
                    ORBlitzaBommer.class,
                    ORWazbomBlastajet.class));
            myChooserGruppen.get(LORD_OF_WAR).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORStompa.class));
        } else if (getFormationType().equals("Deathskulls")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORWarboss.class,
                    ORDeffkillaWartrike.class,
                    null,
                    ORBigMekinMegaArmour.class,
                    ORBigMekwithShokkAttackGun.class,
                    null,
                    ORWeirdboy.class,
                    null,
                    ORKaptinBadrukk.class,
                    null,
                    ORWarbossinMegaArmour.class,
                    ORWarbossonWarbike.class,
                    ORBigMek.class,
                    ORBigMekonWarbike.class));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORBoyz.class,
                    ORGretchin.class));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORMek.class,
                    ORPainboy.class,
                    ORPainboyonWarbike.class,
                    ORRuntherd.class,
                    null,
                    ORBurnaBoyz.class,
                    ORTankbustas.class,
                    ORNobz.class,
                    ORNobwithWaaaghBanner.class,
                    ORNobzonWarbikes.class,
                    ORMeganobz.class,
                    ORKommandos.class,
                    null,
                    ORMadDokGrotsnik.class));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORStormboyz.class,
                    ORDeffkoptas.class,
                    ORWarbikers.class,
                    ORKustomBoostaBlastas.class,
                    ORShokkjumpDragstas.class,
                    ORBoomdakkaSnazzwagons.class,
                    ORRukkatrukkSquigbuggys.class,
                    ORMegatrakkScrapjet.class,
                    null,
                    ORWartrakks.class,
                    ORSkorchas.class,
                    ORWarbuggies.class,
                    null,
                    ORGrotTanks.class,
                    ORGrotMegaTank.class));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORDeffDreads.class,
                    ORKillaKans.class,
                    ORGorkanaut.class,
                    ORMorkanaut.class,
                    ORBattlewagon.class,
                    ORGunwagon.class,
                    ORBonebreaka.class,
                    ORBigGunz.class,
                    ORMekGunz.class,
                    ORLootas.class,
                    ORFlashGitz.class,
                    null,
                    ORSquiggoth.class,
                    ORMekaDread.class,
                    ORLiftaWagon.class,
                    ORBigTrakk.class,
                    ORBattlewagonwithSupaKannon.class));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORTrukk.class));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORDakkajet.class,
                    ORBurnaBommer.class,
                    ORBlitzaBommer.class,
                    ORWazbomBlastajet.class));
            myChooserGruppen.get(LORD_OF_WAR).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORStompa.class));
        } else if (getFormationType().equals("Evil Sunz")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORWarboss.class,
                    ORDeffkillaWartrike.class,
                    null,
                    ORBigMekinMegaArmour.class,
                    ORBigMekwithShokkAttackGun.class,
                    null,
                    ORWeirdboy.class,
                    null,
                    ORKaptinBadrukk.class,
                    null,
                    ORWarbossinMegaArmour.class,
                    ORWarbossonWarbike.class,
                    ORBigMek.class,
                    ORBigMekonWarbike.class,
                    null,
                    ORZhadsnarkdaRippa.class));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORBoyz.class,
                    ORGretchin.class));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORMek.class,
                    ORPainboy.class,
                    ORPainboyonWarbike.class,
                    ORRuntherd.class,
                    null,
                    ORBurnaBoyz.class,
                    ORTankbustas.class,
                    ORNobz.class,
                    ORNobwithWaaaghBanner.class,
                    ORNobzonWarbikes.class,
                    ORMeganobz.class,
                    ORKommandos.class));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORStormboyz.class,
                    ORDeffkoptas.class,
                    ORWarbikers.class,
                    ORKustomBoostaBlastas.class,
                    ORShokkjumpDragstas.class,
                    ORBoomdakkaSnazzwagons.class,
                    ORRukkatrukkSquigbuggys.class,
                    ORMegatrakkScrapjet.class,
                    null,
                    ORWartrakks.class,
                    ORSkorchas.class,
                    ORWarbuggies.class,
                    null,
                    ORGrotTanks.class,
                    ORGrotMegaTank.class));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORDeffDreads.class,
                    ORKillaKans.class,
                    ORGorkanaut.class,
                    ORMorkanaut.class,
                    ORBattlewagon.class,
                    ORGunwagon.class,
                    ORBonebreaka.class,
                    ORBigGunz.class,
                    ORMekGunz.class,
                    ORLootas.class,
                    ORFlashGitz.class,
                    null,
                    ORSquiggoth.class,
                    ORMekaDread.class,
                    ORLiftaWagon.class,
                    ORBigTrakk.class,
                    ORBattlewagonwithSupaKannon.class));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORTrukk.class));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORDakkajet.class,
                    ORBurnaBommer.class,
                    ORBlitzaBommer.class,
                    ORWazbomBlastajet.class));
            myChooserGruppen.get(LORD_OF_WAR).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORStompa.class));
        } else if (getFormationType().equals("Snakebites") || getFormationType().equals("Bad Moonz") || getFormationType().equals("Freebooterz")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
            		null,
                    ORWarboss.class,
                    ORDeffkillaWartrike.class,
                    null,
                    ORBigMekinMegaArmour.class,
                    ORBigMekwithShokkAttackGun.class,
                    null,
                    ORWeirdboy.class,
                    null,
                    ORKaptinBadrukk.class,
                    null,
                    ORWarbossinMegaArmour.class,
                    ORWarbossonWarbike.class,
                    ORBigMek.class,
                    ORBigMekonWarbike.class));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORBoyz.class,
                    ORGretchin.class));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORMek.class,
                    ORPainboy.class,
                    ORPainboyonWarbike.class,
                    ORRuntherd.class,
                    null,
                    ORBurnaBoyz.class,
                    ORTankbustas.class,
                    ORNobz.class,
                    ORNobwithWaaaghBanner.class,
                    ORNobzonWarbikes.class,
                    ORMeganobz.class,
                    ORKommandos.class));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORStormboyz.class,
                    ORDeffkoptas.class,
                    ORWarbikers.class,
                    ORKustomBoostaBlastas.class,
                    ORShokkjumpDragstas.class,
                    ORBoomdakkaSnazzwagons.class,
                    ORRukkatrukkSquigbuggys.class,
                    ORMegatrakkScrapjet.class,
                    null,
                    ORWartrakks.class,
                    ORSkorchas.class,
                    ORWarbuggies.class,
                    null,
                    ORGrotTanks.class,
                    ORGrotMegaTank.class));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORDeffDreads.class,
                    ORKillaKans.class,
                    ORGorkanaut.class,
                    ORMorkanaut.class,
                    ORBattlewagon.class,
                    ORGunwagon.class,
                    ORBonebreaka.class,
                    ORBigGunz.class,
                    ORMekGunz.class,
                    ORLootas.class,
                    ORFlashGitz.class,
                    null,
                    ORSquiggoth.class,
                    ORMekaDread.class,
                    ORLiftaWagon.class,
                    ORBigTrakk.class,
                    ORBattlewagonwithSupaKannon.class));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORTrukk.class));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORDakkajet.class,
                    ORBurnaBommer.class,
                    ORBlitzaBommer.class,
                    ORWazbomBlastajet.class));
            myChooserGruppen.get(LORD_OF_WAR).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    ORStompa.class));
        }

        if (formation != null) {
            formation.refreshControlPanel();
        }

        fillChooserSpace();
    }

    @Override
    public void refreshAction() {
        if (BuildaHQ.getCountFromInformationVectorGlobal("ORZhadsnark") > 0) {
            myChooserGruppen.get(TROOPS).addSpezialAuswahl(ORWarbikers.class);
        } else {
            myChooserGruppen.get(TROOPS).removeSpezialAuswahl(ORWarbikers.class);
        }
        super.refreshAction();
    }
}