package oc.wh40k.armies;

import com.google.common.collect.ImmutableList;
import oc.BuildaHQ;
import oc.BuildaVater;
import oc.utils.ResourceUtils;
import oc.wh40k.units.or.*;

public class VOLKOrks extends BuildaVater {

    public VOLKOrks() {
        super("OR", ResourceUtils.loadPoints("/oc/wh40k/indices/or.yaml"));

        volk = "Orks";
        nameDerArtDerArmee = "Orks";
        nameDerArtDerArmeeDekliniert = "der Orks";

        textAreaUeberschrift = BuildaHQ.translate("Mein") + " Waaagh!";

        formationen.add("ORK");
        formationen.add("Goff");
        formationen.add("Blood Axe");
        formationen.add("Deathskulls");
        formationen.add("Evil Sunz");
        formationen.add("Snakebites");
        formationen.add("Bad Moonz");
        formationen.add("Freebooterz");

        complete();
    }

    @Override
    public void volkRefresh() {
        if (getFormationType().equals("ORK")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORWarboss.class,
                            ORDeffkillaWartrike.class),
                    ImmutableList.of(
                            ORBigMekinMegaArmour.class,
                            ORBigMekwithShokkAttackGun.class),
                    ImmutableList.of(
                            ORWeirdboy.class),
                    ImmutableList.of(
                            ORGhazghkullThraka.class,
                            ORKaptinBadrukk.class,
                            ORBossZagstruk.class,
                            ORBossSnikrot.class),
                    ImmutableList.of(
                            ORWarbossinMegaArmour.class,
                            ORWarbossonWarbike.class,
                            ORBigMek.class,
                            ORBigMekonWarbike.class),
                    ImmutableList.of(
                            ORZhadsnarkdaRippa.class,
                            OROrkMekBossBuzzgob.class)));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORBoyz.class,
                            ORGretchin.class)));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORMek.class,
                            ORPainboy.class,
                            ORRuntherd.class),
                    ImmutableList.of(
                            ORBurnaBoyz.class,
                            ORTankbustas.class,
                            ORKommandos.class),
                    ImmutableList.of(
                            ORNobz.class,
                            ORNobwithWaaaghBanner.class,
                            ORNobzonWarbikes.class,
                            ORMeganobz.class),
                    ImmutableList.of(
                            ORMadDokGrotsnik.class),
                    ImmutableList.of(
                            ORPainboyonWarbike.class)));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORStormboyz.class,
                            ORDeffkoptas.class,
                            ORWarbikers.class),
                    ImmutableList.of(
                            ORKustomBoostaBlastas.class,
                            ORShokkjumpDragstas.class,
                            ORBoomdakkaSnazzwagons.class,
                            ORRukkatrukkSquigbuggys.class,
                            ORMegatrakkScrapjet.class),
                    ImmutableList.of(
                            ORWartrakks.class,
                            ORSkorchas.class,
                            ORWarbuggies.class),
                    ImmutableList.of(
                            ORGrotTanks.class,
                            ORGrotMegaTank.class)));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORDeffDreads.class,
                            ORKillaKans.class),
                    ImmutableList.of(
                            ORGorkanaut.class,
                            ORMorkanaut.class),
                    ImmutableList.of(
                            ORBattlewagon.class,
                            ORGunwagon.class,
                            ORBonebreaka.class),
                    ImmutableList.of(
                            ORMekGunz.class,
                            ORLootas.class,
                            ORFlashGitz.class),
                    ImmutableList.of(
                            ORBigGunz.class),
                    ImmutableList.of(
                            ORSquiggoth.class,
                            ORMekaDread.class,
                            ORLiftaWagon.class,
                            ORBigTrakk.class,
                            ORBattlewagonwithSupaKannon.class)));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORTrukk.class),
                    ImmutableList.of(
                            ORChinorkWarkopta.class)));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORDakkajet.class,
                            ORBurnaBommer.class,
                            ORBlitzaBommer.class,
                            ORWazbomBlastajet.class)));
            myChooserGruppen.get(LORD_OF_WAR).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORStompa.class),
                    ImmutableList.of(
                            ORKillTank.class,
                            ORKustomStompa.class,
                            ORGargantuanSquiggoth.class)));
        } else if (getFormationType().equals("Goff")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORWarboss.class,
                            ORDeffkillaWartrike.class),
                    ImmutableList.of(
                            ORBigMekinMegaArmour.class,
                            ORBigMekwithShokkAttackGun.class),
                    ImmutableList.of(
                            ORWeirdboy.class),
                    ImmutableList.of(
                            ORKaptinBadrukk.class,
                            ORGhazghkullThraka.class,
                            ORBossZagstruk.class),
                    ImmutableList.of(
                            ORWarbossinMegaArmour.class,
                            ORWarbossonWarbike.class,
                            ORBigMek.class,
                            ORBigMekonWarbike.class),
                    ImmutableList.of(
                            OROrkMekBossBuzzgob.class)));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORBoyz.class,
                            ORGretchin.class)));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORMek.class,
                            ORPainboy.class,
                            ORPainboyonWarbike.class,
                            ORRuntherd.class),
                    ImmutableList.of(
                            ORBurnaBoyz.class,
                            ORTankbustas.class,
                            ORNobz.class,
                            ORNobwithWaaaghBanner.class,
                            ORNobzonWarbikes.class,
                            ORMeganobz.class,
                            ORKommandos.class)));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORStormboyz.class,
                            ORDeffkoptas.class,
                            ORWarbikers.class,
                            ORKustomBoostaBlastas.class,
                            ORShokkjumpDragstas.class,
                            ORBoomdakkaSnazzwagons.class,
                            ORRukkatrukkSquigbuggys.class,
                            ORMegatrakkScrapjet.class),
                    ImmutableList.of(
                            ORWartrakks.class,
                            ORSkorchas.class,
                            ORWarbuggies.class),
                    ImmutableList.of(
                            ORGrotTanks.class,
                            ORGrotMegaTank.class)));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORDeffDreads.class,
                            ORKillaKans.class,
                            ORGorkanaut.class,
                            ORMorkanaut.class,
                            ORBattlewagon.class,
                            ORGunwagon.class,
                            ORBonebreaka.class,
                            ORBigGunz.class,
                            ORMekGunz.class,
                            ORLootas.class,
                            ORFlashGitz.class),
                    ImmutableList.of(
                            ORSquiggoth.class,
                            ORMekaDread.class,
                            ORLiftaWagon.class,
                            ORBigTrakk.class,
                            ORBattlewagonwithSupaKannon.class)));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORTrukk.class)));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORDakkajet.class,
                            ORBurnaBommer.class,
                            ORBlitzaBommer.class,
                            ORWazbomBlastajet.class)));
            myChooserGruppen.get(LORD_OF_WAR).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORStompa.class)));
        } else if (getFormationType().equals("Blood Axe")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORWarboss.class,
                            ORDeffkillaWartrike.class),
                    ImmutableList.of(
                            ORBigMekinMegaArmour.class,
                            ORBigMekwithShokkAttackGun.class),
                    ImmutableList.of(
                            ORWeirdboy.class),
                    ImmutableList.of(
                            ORKaptinBadrukk.class,
                            ORBossSnikrot.class),
                    ImmutableList.of(
                            ORWarbossinMegaArmour.class,
                            ORWarbossonWarbike.class,
                            ORBigMek.class,
                            ORBigMekonWarbike.class)));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORBoyz.class,
                            ORGretchin.class)));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORMek.class,
                            ORPainboy.class,
                            ORPainboyonWarbike.class,
                            ORRuntherd.class),
                    ImmutableList.of(
                            ORBurnaBoyz.class,
                            ORTankbustas.class,
                            ORNobz.class,
                            ORNobwithWaaaghBanner.class,
                            ORNobzonWarbikes.class,
                            ORMeganobz.class,
                            ORKommandos.class)));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORStormboyz.class,
                            ORDeffkoptas.class,
                            ORWarbikers.class,
                            ORKustomBoostaBlastas.class,
                            ORShokkjumpDragstas.class,
                            ORBoomdakkaSnazzwagons.class,
                            ORRukkatrukkSquigbuggys.class,
                            ORMegatrakkScrapjet.class),
                    ImmutableList.of(
                            ORWartrakks.class,
                            ORSkorchas.class,
                            ORWarbuggies.class),
                    ImmutableList.of(
                            ORGrotTanks.class,
                            ORGrotMegaTank.class)));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORDeffDreads.class,
                            ORKillaKans.class,
                            ORGorkanaut.class,
                            ORMorkanaut.class,
                            ORBattlewagon.class,
                            ORGunwagon.class,
                            ORBonebreaka.class,
                            ORBigGunz.class,
                            ORMekGunz.class,
                            ORLootas.class,
                            ORFlashGitz.class),
                    ImmutableList.of(
                            ORSquiggoth.class,
                            ORMekaDread.class,
                            ORLiftaWagon.class,
                            ORBigTrakk.class,
                            ORBattlewagonwithSupaKannon.class)));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORTrukk.class)));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORDakkajet.class,
                            ORBurnaBommer.class,
                            ORBlitzaBommer.class,
                            ORWazbomBlastajet.class)));
            myChooserGruppen.get(LORD_OF_WAR).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORStompa.class)));
        } else if (getFormationType().equals("Deathskulls")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORWarboss.class,
                            ORDeffkillaWartrike.class),
                    ImmutableList.of(
                            ORBigMekinMegaArmour.class,
                            ORBigMekwithShokkAttackGun.class),
                    ImmutableList.of(
                            ORWeirdboy.class),
                    ImmutableList.of(
                            ORKaptinBadrukk.class),
                    ImmutableList.of(
                            ORWarbossinMegaArmour.class,
                            ORWarbossonWarbike.class,
                            ORBigMek.class,
                            ORBigMekonWarbike.class)));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORBoyz.class,
                            ORGretchin.class)));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORMek.class,
                            ORPainboy.class,
                            ORPainboyonWarbike.class,
                            ORRuntherd.class),
                    ImmutableList.of(
                            ORBurnaBoyz.class,
                            ORTankbustas.class,
                            ORNobz.class,
                            ORNobwithWaaaghBanner.class,
                            ORNobzonWarbikes.class,
                            ORMeganobz.class,
                            ORKommandos.class),
                    ImmutableList.of(
                            ORMadDokGrotsnik.class)));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORStormboyz.class,
                            ORDeffkoptas.class,
                            ORWarbikers.class,
                            ORKustomBoostaBlastas.class,
                            ORShokkjumpDragstas.class,
                            ORBoomdakkaSnazzwagons.class,
                            ORRukkatrukkSquigbuggys.class,
                            ORMegatrakkScrapjet.class),
                    ImmutableList.of(
                            ORWartrakks.class,
                            ORSkorchas.class,
                            ORWarbuggies.class),
                    ImmutableList.of(
                            ORGrotTanks.class,
                            ORGrotMegaTank.class)));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORDeffDreads.class,
                            ORKillaKans.class,
                            ORGorkanaut.class,
                            ORMorkanaut.class,
                            ORBattlewagon.class,
                            ORGunwagon.class,
                            ORBonebreaka.class,
                            ORBigGunz.class,
                            ORMekGunz.class,
                            ORLootas.class,
                            ORFlashGitz.class),
                    ImmutableList.of(
                            ORSquiggoth.class,
                            ORMekaDread.class,
                            ORLiftaWagon.class,
                            ORBigTrakk.class,
                            ORBattlewagonwithSupaKannon.class)));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORTrukk.class)));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORDakkajet.class,
                            ORBurnaBommer.class,
                            ORBlitzaBommer.class,
                            ORWazbomBlastajet.class)));
            myChooserGruppen.get(LORD_OF_WAR).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORStompa.class)));
        } else if (getFormationType().equals("Evil Sunz")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORWarboss.class,
                            ORDeffkillaWartrike.class),
                    ImmutableList.of(
                            ORBigMekinMegaArmour.class,
                            ORBigMekwithShokkAttackGun.class),
                    ImmutableList.of(
                            ORWeirdboy.class),
                    ImmutableList.of(
                            ORKaptinBadrukk.class),
                    ImmutableList.of(
                            ORWarbossinMegaArmour.class,
                            ORWarbossonWarbike.class,
                            ORBigMek.class,
                            ORBigMekonWarbike.class),
                    ImmutableList.of(
                            ORZhadsnarkdaRippa.class)));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORBoyz.class,
                            ORGretchin.class)));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORMek.class,
                            ORPainboy.class,
                            ORPainboyonWarbike.class,
                            ORRuntherd.class),
                    ImmutableList.of(
                            ORBurnaBoyz.class,
                            ORTankbustas.class,
                            ORNobz.class,
                            ORNobwithWaaaghBanner.class,
                            ORNobzonWarbikes.class,
                            ORMeganobz.class,
                            ORKommandos.class)));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORStormboyz.class,
                            ORDeffkoptas.class,
                            ORWarbikers.class,
                            ORKustomBoostaBlastas.class,
                            ORShokkjumpDragstas.class,
                            ORBoomdakkaSnazzwagons.class,
                            ORRukkatrukkSquigbuggys.class,
                            ORMegatrakkScrapjet.class),
                    ImmutableList.of(
                            ORWartrakks.class,
                            ORSkorchas.class,
                            ORWarbuggies.class),
                    ImmutableList.of(
                            ORGrotTanks.class,
                            ORGrotMegaTank.class)));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORDeffDreads.class,
                            ORKillaKans.class,
                            ORGorkanaut.class,
                            ORMorkanaut.class,
                            ORBattlewagon.class,
                            ORGunwagon.class,
                            ORBonebreaka.class,
                            ORBigGunz.class,
                            ORMekGunz.class,
                            ORLootas.class,
                            ORFlashGitz.class),
                    ImmutableList.of(
                            ORSquiggoth.class,
                            ORMekaDread.class,
                            ORLiftaWagon.class,
                            ORBigTrakk.class,
                            ORBattlewagonwithSupaKannon.class)));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORTrukk.class)));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORDakkajet.class,
                            ORBurnaBommer.class,
                            ORBlitzaBommer.class,
                            ORWazbomBlastajet.class)));
            myChooserGruppen.get(LORD_OF_WAR).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORStompa.class)));
        } else if (getFormationType().equals("Snakebites") || getFormationType().equals("Bad Moonz") || getFormationType().equals("Freebooterz")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORWarboss.class,
                            ORDeffkillaWartrike.class),
                    ImmutableList.of(
                            ORBigMekinMegaArmour.class,
                            ORBigMekwithShokkAttackGun.class),
                    ImmutableList.of(
                            ORWeirdboy.class),
                    ImmutableList.of(
                            ORKaptinBadrukk.class),
                    ImmutableList.of(
                            ORWarbossinMegaArmour.class,
                            ORWarbossonWarbike.class,
                            ORBigMek.class,
                            ORBigMekonWarbike.class)));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORBoyz.class,
                            ORGretchin.class)));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORMek.class,
                            ORPainboy.class,
                            ORPainboyonWarbike.class,
                            ORRuntherd.class),
                    ImmutableList.of(
                            ORBurnaBoyz.class,
                            ORTankbustas.class,
                            ORNobz.class,
                            ORNobwithWaaaghBanner.class,
                            ORNobzonWarbikes.class,
                            ORMeganobz.class,
                            ORKommandos.class)));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORStormboyz.class,
                            ORDeffkoptas.class,
                            ORWarbikers.class,
                            ORKustomBoostaBlastas.class,
                            ORShokkjumpDragstas.class,
                            ORBoomdakkaSnazzwagons.class,
                            ORRukkatrukkSquigbuggys.class,
                            ORMegatrakkScrapjet.class),
                    ImmutableList.of(
                            ORWartrakks.class,
                            ORSkorchas.class,
                            ORWarbuggies.class),
                    ImmutableList.of(
                            ORGrotTanks.class,
                            ORGrotMegaTank.class)));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORDeffDreads.class,
                            ORKillaKans.class,
                            ORGorkanaut.class,
                            ORMorkanaut.class,
                            ORBattlewagon.class,
                            ORGunwagon.class,
                            ORBonebreaka.class,
                            ORBigGunz.class,
                            ORMekGunz.class,
                            ORLootas.class,
                            ORFlashGitz.class),
                    ImmutableList.of(
                            ORSquiggoth.class,
                            ORMekaDread.class,
                            ORLiftaWagon.class,
                            ORBigTrakk.class,
                            ORBattlewagonwithSupaKannon.class)));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORTrukk.class)));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORDakkajet.class,
                            ORBurnaBommer.class,
                            ORBlitzaBommer.class,
                            ORWazbomBlastajet.class)));
            myChooserGruppen.get(LORD_OF_WAR).changeComboBoxAuswahlen(ImmutableList.of(
                    ImmutableList.of(
                            ORStompa.class)));
        }

        if (formation != null) {
            formation.refreshControlPanel();
        }

        fillChooserSpace();
    }

    @Override
    public void refreshAction() {
        if (BuildaHQ.getCountFromInformationVectorGlobal("ORZhadsnark") > 0) {
            myChooserGruppen.get(TROOPS).addSpezialAuswahl(ORWarbikers.class);
        } else {
            myChooserGruppen.get(TROOPS).removeSpezialAuswahl(ORWarbikers.class);
        }
        super.refreshAction();
    }
}