package oc.wh40k.armies;


import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableSet;
import oc.BuildaHQ;
import oc.BuildaVater;
import oc.utils.ResourceUtils;
import oc.wh40k.units.ae.*;

import java.util.Set;


public class VOLKAeldari extends BuildaVater {

	private static final Set<String> CRAFTWORLDS = ImmutableSet.of("Alaitoc", "Biel-Tan", "Iyanden", "Saim-Hann", "Ulthwe");
	private static final Set<String> DRUKHARI = ImmutableSet.of("Kabal of the Black Heart", "Kabal of the Flayed Skull", "Kabal of the Poisoned Tongue", "Kabal of the Obsidian Rose", "Cult of Strife", "Cult of the Cursed Blade", "Cult of the Red Grief", "The Prophets of Flesh", "The Dark Creed", "Coven of Twelve");
	private static final Set<String> HARLEQUINS = ImmutableSet.of("Midnight Sorrow", "Veiled Path", "Frozen Stars", "Dreaming Shadow", "Soaring Spite", "Silent Shroud");

    public VOLKAeldari() {
        super("AE", ResourceUtils.loadPoints("/oc/wh40k/indices/ae.yaml", "/oc/wh40k/indices/de.yaml"));

        nameDerArtDerArmee = BuildaHQ.translate("AELDARI");
        nameDerArtDerArmeeDekliniert = BuildaHQ.translate("AELDARI");
        textAreaUeberschrift = BuildaHQ.translate("Meine") + " " + BuildaHQ.translate("AELDARI");

        formationen.add("AELDARI");
        formationen.add(null);
        formationen.add("ASURYANI");
        CRAFTWORLDS.forEach(craftworld -> formationen.add(craftworld));
        formationen.add("Warhost");
        formationen.add("Spirit Host");
        formationen.add("Aspect Warrior");
        formationen.add(null);
        formationen.add("DRUKHARI");
        DRUKHARI.forEach(drukhari -> formationen.add(drukhari));
        formationen.add("Incubi");
        formationen.add(null);
        formationen.add("HARLEQUINS");
        HARLEQUINS.forEach(harlequins -> formationen.add(harlequins));
        formationen.add(null);
        formationen.add("Ynnari");

        complete();
    }

    @Override
    public void volkRefresh() {
        if (getFormationType().equals("AELDARI")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEAutarch.class,
                    AEAutarchwithSwoopingHawkWings.class,
                    AEAutarchSkyrunner.class,
                    AEFarseer.class,
                    AEFarseerSkyrunner.class,
                    AEWarlock.class,
                    AEWarlockConclave.class,
                    AEWarlockSkyrunner.class,
                    AEWarlockSkyrunnerConclave.class,
                    AESpiritseer.class,
                    null,
                    AEEldradUlthran.class,
                    AEPrinceYriel.class,
                    AEIllicNightspear.class,
                    AEAsurmen.class,
                    AEJainZar.class,
                    AEKarandras.class,
                    AEFuegan.class,
                    AEBaharroth.class,
                    AEMauganRa.class,
                    AEAvatarofKhaine.class,

                    null,
                    AEArchon.class,
                    AESuccubus.class,
                    AEHaemonculus.class,
                    null,
                    AELelithHesperax.class,
                    AEUrienRakarth.class,
                    AEDrazhar.class,

                    null,
                    AETroupeMaster.class,
                    AEShadowseer.class,

                    null,
                    AEYvraine.class,
                    AETheVisarch.class,
                    AETheYncarne.class,
                    null,
                    AEAutarchIndex.class,
                    AEAutarchwithSwoopingHawkWingsIndex.class,
                    AEAutarchwithWarpJumpGeneratorIndex.class,
                    AEAutarchSkyrunnerIndex.class));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEGuardianDefenders.class,
                    AEStormGuardians.class,
                    AERangers.class,
                    AEDireAvengers.class,
                    null,
                    AEKabaliteWarriors.class,
                    AEWyches.class,
                    AEWracks.class,
                    null,
                    AETroupe.class));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEHowlingBanshees.class,
                    AEStrikingScorpions.class,
                    AEFireDragons.class,
                    AEWraithguard.class,
                    AEWraithblades.class,
                    AEBonesinger.class,

                    null,
                    AELhamaean.class,
                    AEMedusae.class,
                    AESslyth.class,
                    AEUrGhul.class,
                    AEKabaliteTrueborn.class,
                    AEHekatrixBloodbrides.class,
                    AEIncubi.class,
                    AEMandrakes.class,
                    AEGrotesques.class,
                    AEBeastmaster.class,

                    null,
                    AEDeathJester.class,
                    AESolitaire.class));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWindriders.class,
                    AESwoopingHawks.class,
                    AEWarpSpiders.class,
                    AEShiningSpears.class,
                    AEVypers.class,
                    null,
                    AEClawedFiends.class,
                    AEKhymerae.class,
                    AERazorwingFlocks.class,
                    AEReavers.class,
                    AEHellions.class,
                    AEScourges.class,

                    null,
                    AESkyweavers.class));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEDarkReapers.class,
                    AEVaulsWrathSupportBattery.class,
                    AEFalcon.class,
                    AEFirePrism.class,
                    AENightSpinner.class,
                    AEWarWalkers.class,
                    AEWraithlord.class,

                    null,
                    AETalos.class,
                    AECronos.class,
                    AERavager.class,
                    null,
                    AEReaper.class,
                    AETantalus.class,
                    null,
                    AEVoidweavers.class));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWaveSerpent.class,
                    null,
                    AERaider.class,
                    AEVenom.class,
                    null,
                    AEStarweaver.class));
            myChooserGruppen.get(LORD_OF_WAR).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWraithknight.class));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AECrimsonHunter.class,
                    AECrimsonHunterExarch.class,
                    AEHemlockWraithfighter.class,
                    null,
                    AERazorwingJetfighter.class,
                    AEVoidraven.class));
        } else if (getFormationType().equals("ASURYANI")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEAutarch.class,
                    AEAutarchwithSwoopingHawkWings.class,
                    AEAutarchSkyrunner.class,
                    AEFarseer.class,
                    AEFarseerSkyrunner.class,
                    AEWarlock.class,
                    AEWarlockConclave.class,
                    AEWarlockSkyrunner.class,
                    AEWarlockSkyrunnerConclave.class,
                    AESpiritseer.class,
                    null,
                    AEEldradUlthran.class,
                    AEPrinceYriel.class,
                    AEIllicNightspear.class,
                    AEAsurmen.class,
                    AEJainZar.class,
                    AEKarandras.class,
                    AEFuegan.class,
                    AEBaharroth.class,
                    AEMauganRa.class,
                    AEAvatarofKhaine.class,
                    null,
                    AEAutarchIndex.class,
                    AEAutarchwithSwoopingHawkWingsIndex.class,
                    AEAutarchwithWarpJumpGeneratorIndex.class,
                    AEAutarchSkyrunnerIndex.class));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEGuardianDefenders.class,
                    AEStormGuardians.class,
                    AERangers.class,
                    AEDireAvengers.class));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEHowlingBanshees.class,
                    AEStrikingScorpions.class,
                    AEFireDragons.class,
                    AEWraithguard.class,
                    AEWraithblades.class,
                    AEBonesinger.class));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWindriders.class,
                    AESwoopingHawks.class,
                    AEWarpSpiders.class,
                    AEShiningSpears.class,
                    AEVypers.class));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEDarkReapers.class,
                    AEVaulsWrathSupportBattery.class,
                    AEFalcon.class,
                    AEFirePrism.class,
                    AENightSpinner.class,
                    AEWarWalkers.class,
                    AEWraithlord.class));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWaveSerpent.class));
            myChooserGruppen.get(LORD_OF_WAR).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWraithknight.class));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AECrimsonHunter.class,
                    AECrimsonHunterExarch.class,
                    AEHemlockWraithfighter.class));
        } else if (getFormationType().equals("Warhost")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEAutarch.class,
                    AEAutarchwithSwoopingHawkWings.class,
                    AEAutarchSkyrunner.class,
                    AEFarseer.class,
                    AEFarseerSkyrunner.class,
                    AEWarlock.class,
                    AEWarlockConclave.class,
                    AEWarlockSkyrunner.class,
                    AEWarlockSkyrunnerConclave.class,
                    null,
                    AEEldradUlthran.class,
                    AEPrinceYriel.class,
                    AEIllicNightspear.class,
                    null,
                    AEAutarchIndex.class,
                    AEAutarchwithSwoopingHawkWingsIndex.class,
                    AEAutarchwithWarpJumpGeneratorIndex.class,
                    AEAutarchSkyrunnerIndex.class));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEGuardianDefenders.class,
                    AEStormGuardians.class,
                    AERangers.class));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWindriders.class,
                    AEVypers.class));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEVaulsWrathSupportBattery.class,
                    AEFalcon.class,
                    AEFirePrism.class,
                    AENightSpinner.class,
                    AEWarWalkers.class));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWaveSerpent.class));
        } else if (getFormationType().equals("Spirit Host")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AESpiritseer.class));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWraithguard.class,
                    AEWraithblades.class));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWraithlord.class));
            myChooserGruppen.get(LORD_OF_WAR).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWraithknight.class));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEHemlockWraithfighter.class));
        } else if (getFormationType().equals("Aspect Warrior")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEAsurmen.class,
                    AEJainZar.class,
                    AEKarandras.class,
                    AEFuegan.class,
                    AEBaharroth.class,
                    AEMauganRa.class,
                    AEAvatarofKhaine.class));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEDireAvengers.class));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEHowlingBanshees.class,
                    AEStrikingScorpions.class,
                    AEFireDragons.class));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AESwoopingHawks.class,
                    AEWarpSpiders.class,
                    AEShiningSpears.class));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEDarkReapers.class));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AECrimsonHunter.class,
                    AECrimsonHunterExarch.class));
        } else if (getFormationType().equals("Ulthwe")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEAutarch.class,
                    AEAutarchwithSwoopingHawkWings.class,
                    AEAutarchSkyrunner.class,
                    AEFarseer.class,
                    AEFarseerSkyrunner.class,
                    AEWarlock.class,
                    AEWarlockConclave.class,
                    AEWarlockSkyrunner.class,
                    AEWarlockSkyrunnerConclave.class,
                    AESpiritseer.class,
                    null,
                    AEEldradUlthran.class,
                    AEAvatarofKhaine.class,
                    null,
                    AEAutarchIndex.class,
                    AEAutarchwithSwoopingHawkWingsIndex.class,
                    AEAutarchwithWarpJumpGeneratorIndex.class,
                    AEAutarchSkyrunnerIndex.class));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEGuardianDefenders.class,
                    AEStormGuardians.class,
                    AERangers.class,
                    AEDireAvengers.class));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEHowlingBanshees.class,
                    AEStrikingScorpions.class,
                    AEFireDragons.class,
                    AEWraithguard.class,
                    AEWraithblades.class,
                    AEBonesinger.class));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWindriders.class,
                    AESwoopingHawks.class,
                    AEWarpSpiders.class,
                    AEShiningSpears.class,
                    AEVypers.class));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEDarkReapers.class,
                    AEVaulsWrathSupportBattery.class,
                    AEFalcon.class,
                    AEFirePrism.class,
                    AENightSpinner.class,
                    AEWarWalkers.class,
                    AEWraithlord.class));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWaveSerpent.class));
            myChooserGruppen.get(LORD_OF_WAR).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWraithknight.class));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AECrimsonHunter.class,
                    AECrimsonHunterExarch.class,
                    AEHemlockWraithfighter.class));
        } else if (getFormationType().equals("Iyanden")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEAutarch.class,
                    AEAutarchwithSwoopingHawkWings.class,
                    AEAutarchSkyrunner.class,
                    AEFarseer.class,
                    AEFarseerSkyrunner.class,
                    AEWarlock.class,
                    AEWarlockConclave.class,
                    AEWarlockSkyrunner.class,
                    AEWarlockSkyrunnerConclave.class,
                    AESpiritseer.class,
                    null,
                    AEPrinceYriel.class,
                    AEAvatarofKhaine.class));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEGuardianDefenders.class,
                    AEStormGuardians.class,
                    AERangers.class,
                    AEDireAvengers.class));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEHowlingBanshees.class,
                    AEStrikingScorpions.class,
                    AEFireDragons.class,
                    AEWraithguard.class,
                    AEWraithblades.class));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWindriders.class,
                    AESwoopingHawks.class,
                    AEWarpSpiders.class,
                    AEShiningSpears.class,
                    AEVypers.class));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEDarkReapers.class,
                    AEVaulsWrathSupportBattery.class,
                    AEFalcon.class,
                    AEFirePrism.class,
                    AENightSpinner.class,
                    AEWarWalkers.class,
                    AEWraithlord.class));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWaveSerpent.class));
            myChooserGruppen.get(LORD_OF_WAR).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWraithknight.class));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AECrimsonHunter.class,
                    AECrimsonHunterExarch.class,
                    AEHemlockWraithfighter.class));
        } else if (getFormationType().equals("Alaitoc")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEAutarch.class,
                    AEAutarchwithSwoopingHawkWings.class,
                    AEAutarchSkyrunner.class,
                    AEFarseer.class,
                    AEFarseerSkyrunner.class,
                    AEWarlock.class,
                    AEWarlockConclave.class,
                    AEWarlockSkyrunner.class,
                    AEWarlockSkyrunnerConclave.class,
                    AESpiritseer.class,

                    null,
                    AEIllicNightspear.class,
                    AEAvatarofKhaine.class,
                    null,
                    AEAutarchIndex.class,
                    AEAutarchwithSwoopingHawkWingsIndex.class,
                    AEAutarchwithWarpJumpGeneratorIndex.class,
                    AEAutarchSkyrunnerIndex.class));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEGuardianDefenders.class,
                    AEStormGuardians.class,
                    AERangers.class,
                    AEDireAvengers.class));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEHowlingBanshees.class,
                    AEStrikingScorpions.class,
                    AEFireDragons.class,
                    AEWraithguard.class,
                    AEWraithblades.class));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWindriders.class,
                    AESwoopingHawks.class,
                    AEWarpSpiders.class,
                    AEShiningSpears.class,
                    AEVypers.class));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEDarkReapers.class,
                    AEVaulsWrathSupportBattery.class,
                    AEFalcon.class,
                    AEFirePrism.class,
                    AENightSpinner.class,
                    AEWarWalkers.class,
                    AEWraithlord.class));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWaveSerpent.class));
            myChooserGruppen.get(LORD_OF_WAR).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWraithknight.class));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AECrimsonHunter.class,
                    AECrimsonHunterExarch.class,
                    AEHemlockWraithfighter.class));
        } else if (getFormationType().equals("DRUKHARI")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEArchon.class,
                    AESuccubus.class,
                    AEHaemonculus.class,
                    null,
                    AELelithHesperax.class,
                    AEUrienRakarth.class,
                    AEDrazhar.class));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEKabaliteWarriors.class,
                    AEWyches.class,
                    AEWracks.class));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AELhamaean.class,
                    AEMedusae.class,
                    AESslyth.class,
                    AEUrGhul.class,
                    AEKabaliteTrueborn.class,
                    AEHekatrixBloodbrides.class,
                    AEIncubi.class,
                    AEMandrakes.class,
                    AEGrotesques.class,
                    AEBeastmaster.class));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEClawedFiends.class,
                    AEKhymerae.class,
                    AERazorwingFlocks.class,
                    AEReavers.class,
                    AEHellions.class,
                    AEScourges.class));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AETalos.class,
                    AECronos.class,
                    AERavager.class,
                    null,
                    AEReaper.class,
                    AETantalus.class));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AERaider.class,
                    AEVenom.class));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AERazorwingJetfighter.class,
                    AEVoidraven.class));
        } else if (getFormationType().equals("Kabal of the Black Heart")
        		|| getFormationType().equals("Flayed Skull")
        		|| getFormationType().equals("Poisoned Tongue")
        		|| getFormationType().equals("Kabal of the Obsidian Rose")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEArchon.class,
                    null,
                    AEDrazhar.class));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEKabaliteWarriors.class));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEKabaliteTrueborn.class,
                    AELhamaean.class,
                    AEMedusae.class,
                    AESslyth.class,
                    AEUrGhul.class,
                    AEIncubi.class,
                    AEMandrakes.class));
        	myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEClawedFiends.class,
                    AEKhymerae.class,
                    AERazorwingFlocks.class,
                    AEScourges.class));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AERavager.class,
                    null,
                    AEReaper.class,
                    AETantalus.class));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AERaider.class,
                    AEVenom.class));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AERazorwingJetfighter.class,
                    AEVoidraven.class));
        } else if (getFormationType().equals("Cult of Strife")
        		|| getFormationType().equals("Cult of the Cursed Blade")
        		|| getFormationType().equals("Cult of the Red Grief")) {
        	if(getFormationType().equals("Cult of Strife")) {
        		myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
        				null,
                    AESuccubus.class,
        				null,
                    AEDrazhar.class,
                    AELelithHesperax.class));
        	} else {
        		myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                        null,
                    AESuccubus.class,
                        null,
                    AEDrazhar.class));
        	}
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWyches.class));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEHekatrixBloodbrides.class,
                    AEIncubi.class,
                    AEMandrakes.class,
                    AEBeastmaster.class));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEClawedFiends.class,
                    AEKhymerae.class,
                    AERazorwingFlocks.class,
                    AEReavers.class,
                    AEHellions.class,
                    AEScourges.class));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEReaper.class,
                    AETantalus.class));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AERaider.class,
                    AEVenom.class));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AERazorwingJetfighter.class,
                    AEVoidraven.class));
        } else if (getFormationType().equals("The Prophets of Flesh")
        		|| getFormationType().equals("The Dark Creed")
        		|| getFormationType().equals("Coven of Twelve")) {
        	if(getFormationType().equals("The Prophets of Flesh")){
	            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
	                    null,
                    AEHaemonculus.class,
	                    null,
                    AEUrienRakarth.class,
                    AEDrazhar.class));
        	} else {
        		myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
	                    null,
                    AEHaemonculus.class,
	                    null,
                    AEDrazhar.class));
        	}
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWracks.class));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEIncubi.class,
                    AEMandrakes.class,
                    AEGrotesques.class));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEClawedFiends.class,
                    AEKhymerae.class,
                    AERazorwingFlocks.class,
                    AEScourges.class));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AETalos.class,
                    AECronos.class,
                    null,
                    AEReaper.class,
                    AETantalus.class));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AERaider.class,
                    AEVenom.class));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(null));
        } else if (getFormationType().equals("Incubi")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEDrazhar.class));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEIncubi.class));
        } else if (getFormationType().equals("HARLEQUINS") || HARLEQUINS.contains(getFormationType())) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AETroupeMaster.class,
                    AEShadowseer.class));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AETroupe.class));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEDeathJester.class,
                    AESolitaire.class));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AESkyweavers.class));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEVoidweavers.class));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEStarweaver.class));
            myChooserGruppen.get(FORTIFICATION).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWebwayGate.class));
        } else if (getFormationType().equals("Ynnari")) {
            myChooserGruppen.get(HQ).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEYvraine.class,
                    AETheVisarch.class,
                    AETheYncarne.class,
                    null,
                    AEAutarch.class,
                    AEAutarchwithSwoopingHawkWings.class,
                    AEAutarchSkyrunner.class,
                    AEFarseer.class,
                    AEFarseerSkyrunner.class,
                    AEWarlock.class,
                    AEWarlockConclave.class,
                    AEWarlockSkyrunner.class,
                    AEWarlockSkyrunnerConclave.class,
                    AESpiritseer.class,
                    null,
                    AEEldradUlthran.class,
                    AEPrinceYriel.class,
                    AEIllicNightspear.class,
                    AEAsurmen.class,
                    AEJainZar.class,
                    AEKarandras.class,
                    AEFuegan.class,
                    AEBaharroth.class,
                    AEMauganRa.class,
                    null,
                    AEArchon.class,
                    AESuccubus.class,
                    null,
                    AELelithHesperax.class,
                    null,
                    AETroupeMaster.class,
                    AEShadowseer.class,
                    null,
                    AEAutarchIndex.class,
                    AEAutarchwithSwoopingHawkWingsIndex.class,
                    AEAutarchwithWarpJumpGeneratorIndex.class,
                    AEAutarchSkyrunnerIndex.class));
            myChooserGruppen.get(TROOPS).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEGuardianDefenders.class,
                    AEStormGuardians.class,
                    AERangers.class,
                    AEDireAvengers.class,
                    null,
                    AEKabaliteWarriors.class,
                    AEWyches.class,
                    null,
                    AETroupe.class));
            myChooserGruppen.get(ELITE).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEHowlingBanshees.class,
                    AEStrikingScorpions.class,
                    AEFireDragons.class,
                    AEWraithguard.class,
                    AEWraithblades.class,
                    null,
                    AELhamaean.class,
                    AEMedusae.class,
                    AESslyth.class,
                    AEUrGhul.class,
                    AEKabaliteTrueborn.class,
                    AEHekatrixBloodbrides.class,
                    AEIncubi.class,
                    AEBeastmaster.class,
                    null,
                    AEDeathJester.class,
                    AESolitaire.class));
            myChooserGruppen.get(FAST_ATTACK).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWindriders.class,
                    AESwoopingHawks.class,
                    AEWarpSpiders.class,
                    AEShiningSpears.class,
                    AEVypers.class,
                    null,
                    AEClawedFiends.class,
                    AEKhymerae.class,
                    AERazorwingFlocks.class,
                    AEReavers.class,
                    AEHellions.class,
                    AEScourges.class,
                    null,
                    AESkyweavers.class));
            myChooserGruppen.get(HEAVY_SUPPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEDarkReapers.class,
                    AEVaulsWrathSupportBattery.class,
                    AEFalcon.class,
                    AEFirePrism.class,
                    AENightSpinner.class,
                    AEWarWalkers.class,
                    AEWraithlord.class,
                    null,
                    AERavager.class,
                    null,
                    AEVoidweavers.class));
            myChooserGruppen.get(DEDICATED_TRANSPORT).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWaveSerpent.class,
                    null,
                    AERaider.class,
                    AEVenom.class,
                    null,
                    AEStarweaver.class));
            myChooserGruppen.get(LORD_OF_WAR).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AEWraithknight.class));
            myChooserGruppen.get(FLIER).changeComboBoxAuswahlen(ImmutableList.of(
                    null,
                    AECrimsonHunter.class,
                    AECrimsonHunterExarch.class,
                    AEHemlockWraithfighter.class,
                    null,
                    AERazorwingJetfighter.class,
                    AEVoidraven.class));
        }

        if (formation != null) {
            formation.refreshControlPanel();
        }

        fillChooserSpace();
    }
}